# -*- coding: utf-8 -*-
"""WEEK - 8

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z8Cee5OwIqyDke4QV3BZqeQGVK6MaCuc

**CELL 1 — IMPORTING LIBRARIES**
"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style="whitegrid")

"""**CELL 2 — LOAD DATASET**"""

df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/train.csv")

print("Dataset Loaded Successfully")

print(df.head())

"""**CELL 3 — DATASET INFORMATION**"""

print(df.info())

"""**CELL 4 — DATA CLEANING & PREPROCESSING**"""

# Convert Date Column into Datetime Format

df['Order Date'] = pd.to_datetime(df['Order Date'],
                                  dayfirst=True)

# Check Missing Values

print(df.isnull().sum())

# Remove Duplicate Rows

print("Duplicate Rows Before Removal :",
      df.duplicated().sum())

df = df.drop_duplicates()

print("Duplicate Rows After Removal :",
      df.duplicated().sum())

# Sort Dataset by Date

df = df.sort_values(by='Order Date')

print("Cleaned Data Shape :", df.shape)

"""**CELL 5 — CREATE DATE FEATURES**"""

df['Year'] = df['Order Date'].dt.year
df['Month'] = df['Order Date'].dt.month
df['Day'] = df['Order Date'].dt.day
df['Day_Name'] = df['Order Date'].dt.day_name()
print(df.head())

"""**CELL 6 — DESCRIPTIVE STATISTICS**"""

print("Total Sales :", df['Sales'].sum())
print("Average Sales :", df['Sales'].mean())
print("Maximum Sales :", df['Sales'].max())
print("Minimum Sales :", df['Sales'].min())
print(df.describe())

"""**CELL 7 — DAILY SALES TREND ANALYSIS**"""

daily_sales = df.groupby('Order Date')['Sales'].sum()
plt.figure(figsize=(14,5))
plt.plot(daily_sales)
plt.title("Daily Sales Trend")
plt.xlabel("Date")
plt.ylabel("Sales")
plt.show()

"""**CELL 8 — MONTHLY SALES ANALYSIS**"""

monthly_sales = df.groupby('Month')['Sales'].sum()
plt.figure(figsize=(10,5))
monthly_sales.plot(kind='bar')
plt.title("Monthly Sales Analysis")
plt.xlabel("Month")
plt.ylabel("Sales")
plt.show()

"""**CELL 9 — YEARLY SALES ANALYSIS**"""

yearly_sales = df.groupby('Year')['Sales'].sum()
plt.figure(figsize=(10,5))
yearly_sales.plot(kind='bar')
plt.title("Yearly Sales Analysis")
plt.xlabel("Year")
plt.ylabel("Sales")
plt.show()

"""**CELL 10 — DAY WISE SALES ANALYSIS**"""

day_sales = df.groupby('Day_Name')['Sales'].sum()
order = ['Monday',
         'Tuesday',
         'Wednesday',
         'Thursday',
         'Friday',
         'Saturday',
         'Sunday']
day_sales = day_sales.reindex(order)
plt.figure(figsize=(10,5))
day_sales.plot(kind='bar')
plt.title("Day Wise Sales Analysis")
plt.xlabel("Day")
plt.ylabel("Sales")
plt.show()

"""**CELL 11 — CATEGORY WISE SALES ANALYSIS**"""

category_sales = df.groupby('Category')['Sales'].sum()
category_sales = category_sales.sort_values(ascending=False)
plt.figure(figsize=(12,5))
category_sales.plot(kind='bar')
plt.title("Category Wise Sales Analysis")
plt.xlabel("Category")
plt.ylabel("Sales")
plt.show()

"""**CELL 12 — PRODUCT WISE SALES ANALYSIS**"""

item_sales = df.groupby('Product Name')['Sales'].sum()
item_sales = item_sales.sort_values(ascending=False)
top_items = item_sales.head(10)
plt.figure(figsize=(12,5))
top_items.plot(kind='bar')
plt.title("Top 10 Best-Selling Products")
plt.xlabel("Product Name")
plt.ylabel("Sales")
plt.show()

"""**CELL 13 — LOW PERFORMING PRODUCTS**"""

low_items = item_sales.tail(10)
print("Low Performing Products")
print(low_items)

"""**CELL 14 — SALES DISTRIBUTION**"""

plt.figure(figsize=(10,5))
sns.histplot(df['Sales'],
             bins=50,
             kde=True)
plt.title("Sales Distribution")
plt.xlabel("Sales")
plt.ylabel("Frequency")
plt.show()

"""**CELL 15 — OUTLIER DETECTION**"""

plt.figure(figsize=(10,5))
sns.boxplot(x=df['Sales'])
plt.title("Sales Outliers")
plt.show()

"""**CELL 16 — RELATIONSHIP ANALYSIS**"""

plt.figure(figsize=(8,5))
sns.heatmap(df.corr(numeric_only=True),
            annot=True,
            cmap='RdPu')
plt.title("Correlation Heatmap")
plt.show()

"""**CELL 17 — SIMPLE SALES FORECASTING**"""

daily_sales_ma = daily_sales.rolling(window=7).mean()
plt.figure(figsize=(14,5))
plt.plot(daily_sales,
         label='Actual Sales')
plt.plot(daily_sales_ma,
         label='7-Day Moving Average')
plt.legend()
plt.title("Sales Forecast Trend")
plt.xlabel("Date")
plt.ylabel("Sales")
plt.show()

"""**CELL 18 — BUSINESS INSIGHTS**"""

print("Top Performing Category :",
      category_sales.idxmax())
print("Best Selling Product :",
      item_sales.idxmax())
print("Peak Sales Month :",
      monthly_sales.idxmax())
print("Lowest Sales Month :",
      monthly_sales.idxmin())

"""**CELL 19 — PROJECT CONCLUSION**"""

print("""
PROJECT CONCLUSION

1. Historical sales data was analyzed successfully
   using Exploratory Data Analysis (EDA).

2. Monthly, yearly, and daily sales trends were identified.

3. Seasonal sales behavior and peak sales periods
   were detected.

4. High-performing product categories and best-selling
   products were identified.

5. Low-performing products were analyzed to support
   business improvement decisions.

6. Correlation analysis helped understand relationships
   between sales-related variables.

7. Data visualization techniques improved understanding
   of sales distribution and trends.

8. Moving Average forecasting helped estimate future
   sales patterns.

9. The project supports:
   • Inventory Management
   • Sales Planning
   • Marketing Strategies
   • Business Decision-Making
""")